version: '3.1'  # Версия синтаксиса Docker Compose, которую использует этот файл.
services:       # Ключевое слово, которое определяет список сервисов (контейнеров) в этом файле.
  rabbitmq:                        # Название сервиса.
    container_name: rabbitmq-01-cn # Название контейнера. cn - container name, для отличия container_name и hostname.
    image: rabbitmq:4-management   # Название используемого образа.
    hostname: rabbitmq-01          # Задаёт имя хоста внутри контейнера
    restart: always                # Говорит Docker автоматически перезапускать контейнер в случае его остановки или падения.
    environment:                   # Определям переменные окружения.
      - RABBITMQ_DEFAULT_USE=rmuser   # Имя пользователя по умолчанию. Теперь, под guest нельзя будет зайти.
      - RABBITMQ_DEFAULT_PASS=rmpass  # Пароль пользователя по умолчанию.
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648  
      # log_levels [{connection,error},{default,error}] - указывает на уровни логирования. В данном случае, уровень логирования для соединения (connection) 
      # установлен как "error", а для остальных компонентов по умолчанию (default) также установлен уровень "error". Это означает, что будут логироваться 
      # только ошибки для указанных компонентов. По умолчанию там info, что слишком много для нагруженных систем.
      # disk_free_limit 2147483648 - Low watermark = 2 GiB (Disk space).
    ports:                        # Проброс портов контейнера на порты хоста.
      - '15672:15672'             # Порт для доступа к веб-интерфейсу управления RabbitMQ.
      - '5672:5672'               # Порт для обмена сообщениями. Пробрасывает порт 5672, который используется для подключения приложений к RabbitMQ через протокол AMQP.
    volumes:                          # Монтирует локальную папку ./rabbitmq на хосте в директорию /var/lib/rabbitmq внутри контейнера.
      - ./rabbitmq:/var/lib/rabbitmq  # Это позволяет сохранять данные RabbitMQ (например, очереди и сообщения) между перезапусками контейнера. Т.е. не потерять данные.
                                      # ./rabbitmq - это относительный пусть где лежит docker-compose.yml на хосте.